[package]
name = "locutus-aft-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true }
locutus-stdlib = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

locutus-aft-interface = { path = "../../interfaces" }

[dev-dependencies]
arbitrary = "1"
once_cell = "1"
locutus-stdlib = { workspace = true, features = ["testing"] }

[lib]
crate-type = ["cdylib"]
