[package]
name = "locutus-node"
version = "0.0.1"
edition = "2021"
rust-version = "1.56.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "node-deploy" 
path = "src/bin/gateway-deploy.rs"
doc = false

[dependencies]
anyhow = "1.0"
arbitrary = { version = "1.0", features = ["derive"] }
async-trait = "0.1.51"
bincode = "1.3"
blake2 = { version =  "0.9.2", features = [ "std" ] }
config = { version = "0.11.0", features = [ "toml" ] } 
crossbeam = "0.8.1"
dashmap = "4.0"
env_logger = "0.9.0"
futures = "0.3.17"
libp2p = { version = "0.39", features = [
    "identify",
    "mplex",
    "noise",
    "tcp-tokio",
    "dns-tokio",
    "yamux"
] }
log = { version = "0.4", features = ["serde"] }
mac_address = "1.1"
once_cell = "1.8"
parking_lot = "0.11.2"
rand = "0.8"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.12", features = ["rt-multi-thread", "sync", "macros"] }
typestate = "0.8.0"
uuid = { version = "0.8", features = ["serde", "v4", "v1"] }
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }
base64 = { version = "0.13.0" }