[package]
name = "locutus-node"
version = "0.0.1"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1"
asynchronous-codec = "0.6"
async-trait = "0.1.52"
bincode = "1"
blake2 = { version =  "0.10", features = [ "std" ] }
config = { version = "0.11.0", features = [ "toml" ] } 
crossbeam = "0.8.1"
dashmap = "5" # See RUSTSEC-2022-0002: Do NOT upgrade to 5.0.0 
directories = "4"
either = "1"
env_logger = "0.9.0"
futures = "0.3.21"
hex = "0.4"
libp2p = { version = "0.42.1", features = [
    "autonat",
    "deflate",
    "dns-tokio",
    "identify",
    "noise",
    "mplex",
    "ping",
    "tcp-tokio",
    "yamux"
], default-features = false }
log = { version = "0.4", features = ["serde"] }
once_cell = "1"
parking_lot = "0.12.0"
rand = "0.8"
serde = { version = "1", features = ["rc", "derive"] }
stretto = { version = "0.3.2", features = ["async"] }
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "fs"] }
unsigned-varint = "0.7"
uuid = { version = "0.8", features = ["serde", "v4", "v1"] }
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }

# internal deps
locutus-runtime = { path = "../locutus-runtime" }

[dev-dependencies]
arbitrary = { version = "1", features = ["derive"] }
itertools = "0.10"
pico-args = "0.4"
