[package]
name = "locutus-node"
version = "0.0.1"
edition = "2021"
rust-version = "1.56.0"
resolver = "2"

[lib]
path = "src/lib.rs"

[[bin]]
name = "node-deploy" 
path = "bin/gateway-deploy.rs"
doc = false

[dependencies]
anyhow = "1.0"
arbitrary = { version = "1.0", features = ["derive"] }
asynchronous-codec = "0.6"
async-trait = "0.1.51"
bincode = "1.3"
blake2 = { version =  "0.10", features = [ "std" ] }
config = { version = "0.11.0", features = [ "toml" ] } 
crossbeam = "0.8.1"
dashmap = "5.0"
either = "^1.0"
env_logger = "0.9.0"
futures = "0.3.17"
hex = "0.4.3"
libp2p = { version = "0.41.1", features = [
    "identify",
    "mplex",
    "noise",
    "tcp-tokio",
    "dns-tokio",
    "ping",
    "yamux"
], default-features = false }
log = { version = "0.4", features = ["serde"] }
once_cell = "1.9"
parking_lot = "0.11.2"
rand = "0.8"
serde = { version = "1.0", features = ["rc"] }
stretto = { version = "0.3.1", features = ["async"] }
thiserror = "1.0"
tokio = { version = "1.15", features = ["rt-multi-thread", "sync", "macros"] }
typestate = "0.8.0"
unsigned-varint = "0.7"
uuid = { version = "0.8", features = ["serde", "v4", "v1"] }
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }

[dev-dependencies]
itertools = "0.10"
pico-args = "0.4"
