[package]
name = "locutus-stdlib"
version = "0.0.2"
edition = "2021"
rust-version = "1.58.0"
publish = true
description = "Locutus P2P network standard library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/freenet/locutus"

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
arrayvec = { version = "0.7", features = ["serde"] }
bincode = "1"
byteorder = "1"
blake2 = { version =  "0.10", features = [ "std" ] }
bs58 = "0.4"
env_logger = "0.9"
log = "0.4"
once_cell = "1"
rmpv = { version = "1"}
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_with = "2"
tar = "0.4.38"
thiserror = "1"
xz2 = { version = "0.1", optional = true }

# internal
locutus-macros = { path = "../locutus-macros", version = "0.0.2" }

[dev-dependencies]
arbitrary = { version = "1", features = ["derive"] }
bincode = "1"
wasmer = { version = "^2.0", features = [ "sys-default", "wat"] }
wasmer-wasi = "2.3"
rand = { version = "0.8", features = ["small_rng"] }

[features]
archive = ["xz2"]
testing = ["arbitrary"]
trace = []
