[package]
name = "locutus-stdlib"
version = "0.0.0"
edition = "2021"
rust-version = "1.58.0"

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
arrayvec = { version = "0.7", features = ["serde"] }
byteorder = "1"
blake2 = { version =  "0.10", features = [ "std" ] }
bs58 = "0.4"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_with = "1"
tar = "0.4.38"
thiserror = "1"
xz2 = { version = "0.1", optional = true }

# internal
locutus-macros = { path = "../locutus-macros" }

[dev-dependencies]
arbitrary = { version = "1", features = ["derive"] }
bincode = "1"
wasmer = { version = "^2.0", features = [ "sys-default", "wat"] }
wasmer-wasi = "*"
rand = { version = "0.8", features = ["small_rng"] }

[features]
testing = ["arbitrary"]
archive = ["xz2"]
