[workspace]
resolver = "2"
members = ["components/token-generator", "contracts/token-allocation-record", "interfaces"]

[workspace.dependencies]
bincode = { version = "1" }
chrono = { version = "0.4", default-features = false, features = ["alloc", "serde"] }
ed25519-dalek = { version = "1", no-default-features = true, features = ["serde"] }
hashbrown = { version = "0.13", features = ["serde"] }
locutus-stdlib = { version = "0.0.3", path = "../../crates/locutus-stdlib" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
