[package]
name = "locutus-dev"
version = "0.0.0"
edition = "2021"
rust-version = "1.58.0"
publish = false

[dependencies]
byteorder = "1"
clap = { version = "3", features = ["derive", "env"] }
crossbeam = "0.8"
either = "1"
tracing = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "fs", "signal"] }
parking_lot = "*"
pico-args = "0.4"
log = "0.4"

serde = "1"
bincode = "1"

# (mp) message pack feature
rmp = { version = "0.8", optional = true }
rmpv = { version = "1", optional = true }

# json feature
serde_json = { version = "1", optional = true }

# internal
locutus-node = { path = "../locutus-node" }
locutus-runtime = { path = "../locutus-runtime" }
locutus-stdlib = { path = "../locutus-stdlib" }

[features]
json = ["serde_json"]
messagepack = ["rmp", "rmpv"]
