[package]
name = "freenet-email-app-web"
version = "0.0.0"
edition = "2021"
rust-version = "1.71.1"
resolver = "2"
publish = false

[dependencies]
freenet-stdlib = { workspace = true, features = ["contract"] }

[lib]
crate-type = ["cdylib"]

[features]
default = ["freenet-main-contract"]
freenet-main-contract = []
