name: Deploy Documentation

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.4.1
        with:
          fetch-depth: 0
      - name: Setup Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: stable
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: cargo-cache-${{ hashFiles('Cargo.lock') }}
      - name: Install dependencies
        run: |
          cargo install mdbook mdbook-mermaid
      - name: Build MDBook
        run: |
          if [ -d "docs" ]; then
            cd docs
            mdbook build
          else
            echo "Docs folder not found."
          fi
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/book
          single-commit: true
